#!/usr/bin/env python3
"""
GitHub PR & Issue Webhook Daemon for Antigravity (Synology NAS)
Listens for GitHub Webhook events on port 8191 (via Synology Reverse Proxy).
Verifies HMAC SHA-256 signatures, analyzes repository context & logs with Gemini AI,
and posts complete implementation plans, bug diagnoses, and reviews to GitHub.
"""

import os
import sys
import json
import hmac
import hashlib
import urllib.request
import urllib.error
import subprocess
from http.server import HTTPServer, BaseHTTPRequestHandler
from socketserver import ThreadingMixIn

PORT = int(os.getenv("PORT", "8191"))
ENV_FILE = os.getenv("ENV_FILE", "/volume1/docker/plextracker/antigravity/.env.local")
WORKSPACE_DIR = os.getenv("WORKSPACE_DIR", "/volume1/docker/plextracker/antigravity/workspace")
DATA_DIR = os.getenv("DATA_DIR", "/data")

# Load .env.local secrets into environment if file exists
def load_env_file():
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    val = val.strip("'\"")
                    os.environ[key.strip()] = val

load_env_file()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", os.getenv("ANTIGRAVITY_TOKEN", os.getenv("GH_TOKEN", "")))
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", os.getenv("GITHUB_WEBHOOK_SECRET", ""))
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", os.getenv("GOOGLE_API_KEY", ""))
DEFAULT_MODEL = os.getenv("DEFAULT_MODEL", "gemini-3.6-flash")

DAEMON_SIGNATURE = "<!-- antigravity-daemon -->"
ALLOWED_TRIGGERS = ["/antigravity", "/plextracker", "/bot", "/agy"]


def post_github_comment(repo_full_name, issue_number, body):
    """Post a comment to a GitHub Issue/PR."""
    if not GITHUB_TOKEN:
        print("[ERROR] GITHUB_TOKEN not set, cannot post comment to GitHub.", flush=True)
        return False

    if not body.startswith(DAEMON_SIGNATURE):
        body = f"{DAEMON_SIGNATURE}\n{body}"

    url = f"https://api.github.com/repos/{repo_full_name}/issues/{issue_number}/comments"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Antigravity-NAS-Daemon",
        "Content-Type": "application/json"
    }
    data = json.dumps({"body": body}).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")

    try:
        with urllib.request.urlopen(req) as resp:
            print(f"[INFO] Comment posted successfully to {repo_full_name}#{issue_number} (status {resp.status})", flush=True)
            return True
    except urllib.error.HTTPError as e:
        err_body = e.read().decode('utf-8', errors='ignore')
        print(f"[ERROR] Failed to post comment: {e.code} {e.reason} - {err_body}", flush=True)
        return False
    except Exception as e:
        print(f"[ERROR] Exception posting comment: {e}", flush=True)
        return False


def is_daemon_comment(body):
    """Check if the comment was generated by the daemon itself to prevent loops."""
    if not body:
        return False
    if DAEMON_SIGNATURE in body:
        return True
    if "🤖 **Antigravity NAS Agent**" in body or "### 📋 Antigravity" in body or "❌ **Antigravity Daemon Error**" in body or "❌ **Git Execution Error on NAS:**" in body:
        return True
    return False


def is_trigger_present(*texts):
    """Check if any trigger command is present in non-quoted lines of the provided texts."""
    for text in texts:
        if not text:
            continue
        # Filter out quote lines (starting with >) to avoid loop when quoting previous messages
        clean_lines = [line for line in text.splitlines() if not line.strip().startswith(">")]
        clean_text = "\n".join(clean_lines).lower()
        if any(tr in clean_text for tr in ALLOWED_TRIGGERS):
            return True
    return False


def verify_signature(body_bytes, signature_header):
    """Verify HMAC SHA-256 signature from GitHub."""
    if not WEBHOOK_SECRET:
        print("[WARN] WEBHOOK_SECRET not configured; skipping HMAC verification.", flush=True)
        return True

    if not signature_header or not signature_header.startswith("sha256="):
        return False

    expected_sig = "sha256=" + hmac.new(
        WEBHOOK_SECRET.encode("utf-8"),
        body_bytes,
        hashlib.sha256
    ).hexdigest()

    return hmac.compare_digest(expected_sig, signature_header)


def call_gemini_api(prompt, model_name=DEFAULT_MODEL):
    """Call Google Gemini API to generate content with API key and model fallback."""
    keys = [k.strip() for k in GEMINI_API_KEY.split(",") if k.strip()]
    if not keys:
        raise ValueError("GEMINI_API_KEY not configured on NAS.")

    # Candidate models in priority order
    if "pro" in model_name.lower():
        candidate_models = ["gemini-3.6-pro", "gemini-2.5-pro", "gemini-1.5-pro"]
    else:
        candidate_models = ["gemini-3.6-flash", "gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash"]

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 8192
        }
    }
    data = json.dumps(payload).encode("utf-8")

    last_err = None
    for model in candidate_models:
        for key in keys:
            api_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"
            req = urllib.request.Request(
                api_url,
                data=data,
                headers={"Content-Type": "application/json"},
                method="POST"
            )
            try:
                with urllib.request.urlopen(req, timeout=90) as resp:
                    result = json.loads(resp.read().decode("utf-8"))
                    candidates = result.get("candidates", [])
                    if candidates:
                        parts = candidates[0].get("content", {}).get("parts", [])
                        if parts and "text" in parts[0]:
                            return parts[0]["text"], model
                    raise ValueError(f"Empty response from Gemini API: {result}")
            except urllib.error.HTTPError as e:
                err_msg = e.read().decode("utf-8", errors="ignore")
                print(f"[WARN] Gemini API error (model {model}, status {e.code}): {err_msg}", flush=True)
                last_err = f"HTTP {e.code} (model {model}): {err_msg}"
                if e.code == 404:
                    # Model not found, try next candidate model
                    break
                elif e.code in (429, 500, 503):
                    # Rate limit or temporary error, try next key
                    continue
                break
            except Exception as e:
                print(f"[WARN] Gemini API call failed: {e}", flush=True)
                last_err = str(e)
                continue

    raise RuntimeError(f"Gemini API generation failed. Last error: {last_err}")


def gather_repo_context(repo_dir):
    """Read essential context and documentation files from repository."""
    context_chunks = []
    
    docs_to_read = [
        "AGENTS.md",
        "docs/INDEX.md",
        "docs/maintenance.md",
        "docs/patterns.md"
    ]
    for rel_path in docs_to_read:
        abs_path = os.path.join(repo_dir, rel_path)
        if os.path.exists(abs_path):
            try:
                with open(abs_path, "r", encoding="utf-8") as f:
                    content = f.read(4000)
                    context_chunks.append(f"### File: `{rel_path}`\n```markdown\n{content}\n```")
            except Exception as e:
                print(f"[DEBUG] Could not read {rel_path}: {e}", flush=True)

    # Read recent logs if available (from /data/plextracker.log or repo data)
    log_candidates = [
        os.path.join(DATA_DIR, "plextracker.log"),
        "/volume1/docker/plextracker/data/plextracker.log",
        os.path.join(repo_dir, "data", "plextracker.log")
    ]
    for log_path in log_candidates:
        if os.path.exists(log_path):
            try:
                with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                    lines = f.readlines()
                    last_lines = lines[-120:] if len(lines) > 120 else lines
                    context_chunks.append(f"### Recent Production Logs (`{log_path}` - last {len(last_lines)} lines):\n```log\n{''.join(last_lines)}\n```")
                    break
            except Exception as e:
                print(f"[DEBUG] Could not read log at {log_path}: {e}", flush=True)

    return "\n\n".join(context_chunks)


def process_pr_command(repo_full_name, pr_number, branch_name, clone_url, comment_body, user_login):
    """Process a PR request/command from GitHub."""
    print(f"[INFO] Processing request from {user_login} on {repo_full_name}#{pr_number} (branch: {branch_name})", flush=True)

    # Determine model override if specified in comment
    model_choice = DEFAULT_MODEL
    if "--model=pro" in comment_body.lower() or "model pro" in comment_body.lower():
        model_choice = "gemini-2.5-pro"
    elif "--model=flash" in comment_body.lower() or "model flash" in comment_body.lower():
        model_choice = "gemini-2.0-flash"

    # Ack comment on PR
    ack_msg = f"🤖 **Antigravity NAS Agent** received your request!\n- **Branch**: `{branch_name}`\n- **Model**: `{model_choice}`\n- **Status**: Analyzing repository and logs to prepare implementation plan..."
    post_github_comment(repo_full_name, pr_number, ack_msg)

    # Prepare local workspace
    os.makedirs(WORKSPACE_DIR, exist_ok=True)
    repo_dir = os.path.join(WORKSPACE_DIR, repo_full_name.replace("/", "_"))

    try:
        auth_clone_url = clone_url.replace("https://", f"https://x-access-token:{GITHUB_TOKEN}@")
        if not os.path.exists(os.path.join(repo_dir, ".git")):
            subprocess.run(["git", "clone", auth_clone_url, repo_dir], check=True, capture_output=True, text=True)
        else:
            subprocess.run(["git", "remote", "set-url", "origin", auth_clone_url], cwd=repo_dir, check=True, capture_output=True, text=True)

        subprocess.run(["git", "config", "user.name", "Antigravity NAS Agent"], cwd=repo_dir, check=True, capture_output=True, text=True)
        subprocess.run(["git", "config", "user.email", "antigravity-bot@plextracker.local"], cwd=repo_dir, check=True, capture_output=True, text=True)

        # Fetch and checkout target branch
        subprocess.run(["git", "fetch", "origin"], cwd=repo_dir, check=True, capture_output=True, text=True)
        subprocess.run(["git", "checkout", branch_name], cwd=repo_dir, check=True, capture_output=True, text=True)
        subprocess.run(["git", "pull", "origin", branch_name], cwd=repo_dir, check=True, capture_output=True, text=True)

        # Ensure .env.local is available inside the repository directory
        repo_env = os.path.join(repo_dir, ".env.local")
        if os.path.exists(ENV_FILE):
            import shutil
            shutil.copy(ENV_FILE, repo_env)

        # Clean trigger strings from user message
        clean_user_body = "\n".join(
            line for line in comment_body.strip().splitlines()
            if not any(tr in line.lower() for tr in ALLOWED_TRIGGERS)
        ).strip()
        if not clean_user_body:
            clean_user_body = comment_body.strip()

        # Gather repository docs & recent logs
        repo_context = gather_repo_context(repo_dir)

        # Build prompt for Gemini
        system_prompt = f"""You are Antigravity, an expert senior AI engineer responsible for PlexTracker (a media tracking platform in Go 1.24, SQLite, chi router, Preact 10, Vite, Docker, running on a Synology DS920+ NAS).

You are reviewing a request/issue from the developer @{user_login}.
Repository: {repo_full_name} (target branch: {branch_name})

---
## DEVELOPER REQUEST / ISSUE:
{clean_user_body}

---
## REPOSITORY CONTEXT & SYSTEM LOGS:
{repo_context}

---
## INSTRUCTIONS:
1. Provide a clear, thorough technical analysis of the problem or feature requested.
2. If it's a bug report (e.g. Jellyfin sync, matching, queue, database), inspect the logs/context to identify the exact cause (missing webhook, auth token, matching failure, error in background task, etc.).
3. Propose a concrete Step-by-Step Implementation Plan:
   - Specify files to modify or create with exact function/struct names.
   - Outline code changes concisely.
4. Provide a Verification Plan:
   - Automated tests (`make test`, `make test-front`).
   - Manual verification steps.
5. Format your response cleanly in GitHub Flavored Markdown (in French, matching the user's language). Keep it structured with clear headings.
"""

        print(f"[INFO] Generating AI response with model {model_choice}...", flush=True)
        plan_text, used_model = call_gemini_api(system_prompt, model_choice)

        response_body = (
            f"### 📋 Antigravity Plan & Analysis\n\n"
            f"**Demande de @{user_login}:**\n> {clean_user_body}\n\n"
            f"**Workspace**: `{repo_full_name}` (Branche: `{branch_name}`)\n"
            f"**Modèle utilisé**: `{used_model}`\n\n"
            f"---\n\n"
            f"{plan_text}\n\n"
            f"---\n"
            f"💡 *Pour exécuter ce plan et pousser les modifications sur la branche, répondez avec **`/antigravity Approved`** ou **`/antigravity LGTM`**.*"
        )

        post_github_comment(repo_full_name, pr_number, response_body)

    except subprocess.CalledProcessError as e:
        err_msg = f"❌ **Git Execution Error on NAS:**\n```\n{e.stderr or e.stdout or str(e)}\n```"
        post_github_comment(repo_full_name, pr_number, err_msg)
    except Exception as e:
        err_msg = f"❌ **Antigravity Daemon Error:** `{str(e)}`"
        post_github_comment(repo_full_name, pr_number, err_msg)


class ThreadingHTTPServer(ThreadingMixIn, HTTPServer):
    daemon_threads = True


class WebhookHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        """Health check endpoint."""
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        status = {
            "status": "online",
            "service": "Antigravity GitHub PR Daemon",
            "nas_host": "Synology DS920+",
            "default_model": DEFAULT_MODEL,
            "triggers": ALLOWED_TRIGGERS,
            "webhook_secret_set": bool(WEBHOOK_SECRET),
            "github_token_set": bool(GITHUB_TOKEN),
            "gemini_api_key_set": bool(GEMINI_API_KEY)
        }
        self.wfile.write(json.dumps(status, indent=2).encode("utf-8"))

    def do_POST(self):
        """GitHub Webhook receiver."""
        content_length = int(self.headers.get("Content-Length", 0))
        body_bytes = self.rfile.read(content_length)

        # HMAC verification
        sig_header = self.headers.get("X-Hub-Signature-256", "")
        if not verify_signature(body_bytes, sig_header):
            print("[WARN] Invalid HMAC signature received!", flush=True)
            self.send_response(401)
            self.end_headers()
            self.wfile.write(b'{"error":"Invalid signature"}')
            return

        event_type = self.headers.get("X-GitHub-Event", "")
        print(f"[INFO] Received GitHub event: {event_type}", flush=True)

        try:
            payload = json.loads(body_bytes.decode("utf-8"))
        except json.JSONDecodeError:
            self.send_response(400)
            self.end_headers()
            self.wfile.write(b'{"error":"Invalid JSON"}')
            return

        self.send_response(202)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"status":"accepted"}')

        # Handle events
        if event_type == "issue_comment" and payload.get("action") == "created":
            comment = payload.get("comment", {})
            body = comment.get("body", "")
            user = comment.get("user", {}).get("login", "")
            issue = payload.get("issue", {})
            issue_number = issue.get("number")

            # Check if this comment is from a bot or generated by the daemon itself
            if comment.get("user", {}).get("type") == "Bot" or is_daemon_comment(body):
                print(f"[INFO] Ignoring bot/daemon comment on issue #{issue_number}", flush=True)
                return

            # Only process if comment contains a recognized trigger in non-quoted content
            if is_trigger_present(body):
                repo_full_name = payload.get("repository", {}).get("full_name")
                clone_url = payload.get("repository", {}).get("clone_url")
                pr_info = issue.get("pull_request")

                if pr_info:
                    # It's a Pull Request
                    pr_url = pr_info.get("url")
                    if pr_url and GITHUB_TOKEN:
                        req = urllib.request.Request(
                            pr_url,
                            headers={
                                "Authorization": f"token {GITHUB_TOKEN}",
                                "Accept": "application/vnd.github.v3+json",
                                "User-Agent": "Antigravity-NAS-Daemon"
                            }
                        )
                        try:
                            with urllib.request.urlopen(req) as resp:
                                pr_data = json.loads(resp.read().decode("utf-8"))
                                branch_name = pr_data.get("head", {}).get("ref")
                                process_pr_command(repo_full_name, issue_number, branch_name, clone_url, body, user)
                        except Exception as e:
                            print(f"[ERROR] Failed to fetch PR branch details: {e}", flush=True)
                else:
                    # It's a pure Issue -> process on main / issue feature branch
                    branch_name = f"antigravity/issue-{issue_number}"
                    process_pr_command(repo_full_name, issue_number, "main", clone_url, body, user)

        elif event_type == "issues" and payload.get("action") in ["opened", "reopened"]:
            issue = payload.get("issue", {})
            body = issue.get("body") or ""
            title = issue.get("title") or ""
            user = issue.get("user", {}).get("login", "")
            issue_number = issue.get("number")
            repo_full_name = payload.get("repository", {}).get("full_name")
            clone_url = payload.get("repository", {}).get("clone_url")

            if not is_daemon_comment(body) and is_trigger_present(body, title):
                process_pr_command(repo_full_name, issue_number, "main", clone_url, f"{title}\n{body}", user)

        elif event_type == "pull_request" and payload.get("action") in ["opened", "reopened"]:
            pr = payload.get("pull_request", {})
            body = pr.get("body") or ""
            title = pr.get("title") or ""
            user = pr.get("user", {}).get("login", "")
            pr_number = pr.get("number")
            repo_full_name = payload.get("repository", {}).get("full_name")
            clone_url = payload.get("repository", {}).get("clone_url")
            branch_name = pr.get("head", {}).get("ref")

            if not is_daemon_comment(body) and is_trigger_present(body, title):
                process_pr_command(repo_full_name, pr_number, branch_name, clone_url, f"{title}\n{body}", user)


if __name__ == "__main__":
    print(f"🚀 Starting Antigravity GitHub PR Webhook Daemon on port {PORT}...", flush=True)
    print(f"   Environment file: {ENV_FILE}", flush=True)
    print(f"   Workspace: {WORKSPACE_DIR}", flush=True)
    print(f"   Default Model: {DEFAULT_MODEL}", flush=True)
    server = ThreadingHTTPServer(("0.0.0.0", PORT), WebhookHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping daemon server...", flush=True)
        server.server_close()
